// <auto-generated />
namespace Cotizaciones.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class StepTolerance4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StepTolerance4));
        
        string IMigrationMetadata.Id
        {
            get { return "201502091604188_StepTolerance4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
