// <auto-generated />
namespace Cotizaciones.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Changedorderidentifiertostring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changedorderidentifiertostring));
        
        string IMigrationMetadata.Id
        {
            get { return "201503132110564_Changed order identifier to string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
