// <auto-generated />
namespace Cotizaciones.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Addednewstepchange2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addednewstepchange2));
        
        string IMigrationMetadata.Id
        {
            get { return "201502191821176_Added new step change 2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
