// <auto-generated />
namespace Cotizaciones.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Addedstepchange3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedstepchange3));
        
        string IMigrationMetadata.Id
        {
            get { return "201502191746354_Added step change 3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
